name: brew test-bot
on:
  pull_request:
    branches:
      - main
    paths:
      # Only run this for changes to the formulas
      - "Formula/*.rb"
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae --root-url=https://ghcr.io/v2/overmindtech/overmind
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
  notify:
    runs-on: ubuntu-latest
    needs: test-bot
    if: always()
    steps:
      - name: Load Slack webhook secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_RO_TOKEN }}
          SLACK_WEBHOOK_ENG_BOTS: op://global/Slack GitOps Receiver App/eng_bots_hook_url
          SLACK_WEBHOOK_ENGINEERING: op://global/Slack GitOps Receiver App/engineering_hook_url

      - name: Notify Slack - Bottling Success
        if: needs.test-bot.result == 'success'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ env.SLACK_WEBHOOK_ENG_BOTS }}
          webhook-type: incoming-webhook
          payload: |
            text: ":white_check_mark: *Homebrew bottling finished*\nPre-compiled bottles created and uploaded. Time to add the `pr-pull` label!\n${{ github.event.pull_request.html_url }}"

      - name: Notify Slack - Bottling Failure
        if: needs.test-bot.result == 'failure'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ env.SLACK_WEBHOOK_ENGINEERING }}
          webhook-type: incoming-webhook
          payload: |
            text: ":x: *Homebrew bottling failed*\ntest-bot failed for ${{ github.event.pull_request.html_url }}\nResults: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
